---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-pvc-redis-deployment
  labels:
    app: redis-pvc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pvc-app
  template:
    metadata:
      labels:
        app: redis-pvc-app
    spec:
      containers:
        - name: redis-prod
          image: redis
          volumeMounts:
          - name: redis-jasmineeds-data-prod
            mountPath: "/data"
      volumes:
      - name: redis-jasmineeds-data-prod
        persistentVolumeClaim:
          claimName: redis-jasmineeds-data-prod
