---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-nodeport-service-prod
spec:
  type: NodePort
  selector:
    app: flask-api-prod
  ports:
  - name: flask-api-prod
    port: 5000
    targetPort: 5000
