---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment-prod
  labels:
    app: redis-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-prod
  template:
    metadata:
      labels:
        app: redis-prod
    spec:
      containers:
        - name: redis-prod
          image: redis:7
          ports:
          - containerPort: 6379
