---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-service-prod
spec:
  type: ClusterIP
  selector:
    app: flask-api-prod
  ports:
  - name: flask-api-prod
    port: 5000
    targetPort: 5000
